### ISSUE TITLE
Text about articles not converted to white on dark

### ISSUE THREAD

**Issue by flashcode** [pedrolucasmag/darkgnews#1]
Hi,

I noticed one text is not converted to white on dark text and then is not readable:

![image](https://user-images.githubusercontent.com/1776783/97807860-9ad62e80-1c63-11eb-9ef5-cd457d05cfaa.png)

Here's the inspect of this text:

![image](https://user-images.githubusercontent.com/1776783/97807992-38c9f900-1c64-11eb-8c63-0c1364afa927.png)

Note: this text seems to be displayed in the French version of Google News but it not displayed in English version (this is probably why you missed it).
The text is "Comment les articles sont-ils classés ?" (which could be translated to: "How are the articles classified?").

By the way if someone knows how to remove this useless text, please tell me.

Thank you for this extension!
And I hope Google will provide a dark theme in future.

**Comment by flashcode** [comment]
Hi,

I want to add that maybe the site has changed since my screenshots above, because now the search field is displayed in white:

![image](https://user-images.githubusercontent.com/1776783/99715379-111dc200-2aa7-11eb-80e3-9a9a13bf1e50.png)

Note: this happens in all languages, not only French.

**Comment by flashcode** [comment]
Thanks for the fix!

**Comment by flashcode** [comment]
Google just added a dark theme on Google News!
I can now remove this extension, thanks for your work which was useful anyway! 👍🏼

**Comment by pedrolucasmag** [comment]
> Google just added a dark theme on Google News!
> I can now remove this extension, thanks for your work which was useful anyway! 👍🏼

Oh, good news! In my browser it hasn't appeared yet, I think they are still experimenting. I'll wait for the full implementation to unpublish the extension in Google Chrome / Mozilla Firefox

Thank you for letting me know!
